# 1. Write a NumPy program to create an array of 10 zeros, array of 10 ones, and array of 10 fives.

In [24]:
import numpy as np

In [6]:
zeros=np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
ones=np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
fives=np.full(10,5)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# 2. Write a NumPy program to create an array of all even integers from 30 to 70

In [32]:
evens=np.arange(30,72,2)
evens

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 3. Write a NumPy program to create an array of given shape (5,6) and integer type, filled with zeros

In [10]:
zeros_array=np.zeros((5,6),dtype=int)
zeros_array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 4. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
random_values=np.random.random((10,10))
print(random_values)
print(random_values.max())
print(random_values.min())

[[0.58957609 0.32564454 0.69452872 0.74042059 0.88192595 0.97266653
  0.46439547 0.16555757 0.62099193 0.3753668 ]
 [0.15966623 0.90805465 0.2960478  0.79488299 0.29659006 0.07111231
  0.66165118 0.25034761 0.97176757 0.0816066 ]
 [0.29283079 0.35869167 0.70292031 0.84640632 0.29981418 0.53205905
  0.36757091 0.95530318 0.87167334 0.25979158]
 [0.98088099 0.57841676 0.07335364 0.79919311 0.38426832 0.68980721
  0.97272269 0.86304008 0.2827946  0.10511117]
 [0.27458731 0.63127135 0.75769192 0.3511962  0.46302268 0.92725751
  0.01679015 0.4208324  0.94910294 0.2057905 ]
 [0.64314227 0.59428081 0.02478096 0.39873701 0.95486445 0.26308445
  0.84632474 0.42101429 0.41197234 0.89885359]
 [0.01165773 0.30601721 0.45545499 0.25423461 0.91446853 0.88857514
  0.48956942 0.4647094  0.81153795 0.99227601]
 [0.8276672  0.56151754 0.68367556 0.74691183 0.0463865  0.2582193
  0.30036816 0.70267792 0.96635503 0.223011  ]
 [0.71320761 0.43412499 0.41089803 0.72084565 0.19848295 0.03287594
  0.02053896 

# 5. Write a NumPy program to create a 3x3 array with values ranging from 2 to 10.

In [44]:
num_array=np.arange(2,11).reshape(3,3)
num_array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 6. Write a NumPy program to create an array of size = 20 using arrange, then extract all numbers from a given array greater than 15.


In [36]:
array_of_20=np.arange(20)
print(array_of_20)
array_of_20[array_of_20 > 15]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([16, 17, 18, 19])

# 7. Write a NumPy program to combine the two 2-dimensional arrays using hstack and vstack.
# Array 1: [[0, 1, 3], [5, 7, 9]]
# Array 2: [[0, 2, 4], [6, 8, 10]]


In [37]:
array_1=np.array([[0, 1, 3], [5, 7, 9]])
array_2=np.array([[0, 2, 4], [6, 8, 10]])
horizontal_merge=np.hstack((array_1,array_2))
print(horizontal_merge)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [38]:
horizontal_merge=np.hstack((array_1,array_2))
vertical_merge=np.vstack((array_1,array_2))
print(vertical_merge)

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


# 8. Write a NumPy program to create ones array of size 10 and change the 6th element to 11

In [39]:
ones_arr=np.ones(10,dtype=int)
ones_arr[5]=11
print(ones_arr)

[ 1  1  1  1  1 11  1  1  1  1]


# 9. Write a NumPy program to append a value to the end of an array.

In [40]:
my_array=np.array([1,2,3,4])
new_arr=np.append(my_array,5)
print(my_array)
print(new_arr)

[1 2 3 4]
[1 2 3 4 5]


# 10.Write a NumPy program to reverse an array [using two different methods].

In [41]:
#first method
my_arr=np.array([10,20,30,40])
reversed_arr=my_arr[::-1]
print(my_arr)
print(reversed_arr)

[10 20 30 40]
[40 30 20 10]


In [42]:
#second method
my_arr=np.array([10,20,30,40])
reversed_list=[my_arr[i] for i in range(len(my_arr)-1,-1,-1)]
reversed_arr=np.array(reversed_list)
print(my_arr)
print(reversed_arr)

[10 20 30 40]
[40 30 20 10]
